name = "RigidBodyTools"
uuid = "befc5f09-81d5-499c-a4b2-d0464ba9f9c8"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
repo = "https://github.com/JuliaIBPM/RigidBodyTools.jl.git"
version = "0.1.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Dierckx = "^0"
DocStringExtensions = "^0"
ForwardDiff = "^0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"


[targets]
test = ["Test", "Random"]
